name: Build & Deploy React to Hostinger (FTP)

on:
  push:
    branches: ["main"]

env:
  BUILD_DIR: build
  NODE_VERSION: "20"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new-website/portfolio
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build React app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: new-website/portfolio/${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.HOSTINGER_SERVER }} # Server IP from hPanel
          username: ${{ secrets.HOSTINGER_USERNAME }} # e.g. u574235449.Ace
          password: ${{ secrets.HOSTINGER_PASSWORD }} # FTP password you set
          protocol: ftps
          port: 21
          local-dir: ./site/ # built React files
          server-dir: / # root of this FTP user (public_html)
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            # **/.htaccess   # uncomment if**
