name: Build & Deploy React to Hostinger (FTP)

on:
  push:
    branches: [ "main" ]

env:
  BUILD_DIR: build
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new-website/portfolio
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: new-website/portfolio/${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.HOSTINGER_SERVER }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./site/
          server-dir: ${{ secrets.HOSTINGER_REMOTE_DIR }}/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            # uncomment next line if you keep a hand-edited .htaccess on the server
            # **/.htaccess
          # set to true if you want the server cleaned before upload
          # dangerous-clean-slate: true
